# .yarnrc.yml
supportedArchitectures:
  os: ["linux", "darwin", "win32"]
  cpu: ["arm64", "x64", "ia32"]

enableGlobalCache: false

# Optional: Configure network settings for better cross-platform compatibility
httpRetry: 3
httpTimeout: 60000

# Optional: Enable better error messages
enableInlineBuilds: false

# Optional: Ensure consistent behavior across platforms
enableStrictSemver: true